In [2]:
import numpy as np

In [22]:
a = np.array([1,5342,32,45,3467,543,6,435,76345,67,54678,68,6,345,23,465])
n = 5

np.argsort(a)

array([ 0,  6, 12, 14,  2,  3,  9, 11, 13,  7, 15,  5,  4,  1, 10,  8])

In [3]:
indices = b[np.argsort(-a[b])]
print(indices)

[ 8 10  1  4  5]


In [4]:
i = 0
k = 5
dists = np.random.rand(10,20)
ind = np.argpartition(dists[i], -k)[-k:]
closest_y = ind[np.argsort(-dists[i][ind])]

In [3]:
np.sqrt(2)

1.4142135623730951

In [13]:
a = [np.random.rand(10,2), np.random.rand(10,2), np.random.rand(10,2)]
b = [np.random.rand(10,12)]
print(a[:1])
print(a[1:2])
print(np.concatenate(a[:1]+a[1:2]))

[array([[0.46160127, 0.89963258],
       [0.41333744, 0.75996015],
       [0.67025035, 0.47658527],
       [0.91930096, 0.43668071],
       [0.71748236, 0.25528005],
       [0.30764393, 0.14536158],
       [0.8710383 , 0.63843333],
       [0.65006316, 0.0945142 ],
       [0.80291679, 0.45929576],
       [0.76066655, 0.38980491]])]
[array([[0.83496118, 0.44144712],
       [0.39277973, 0.02290792],
       [0.40894774, 0.46248443],
       [0.34993193, 0.10381095],
       [0.23810143, 0.86386031],
       [0.19412545, 0.29766702],
       [0.46487519, 0.72381309],
       [0.79935101, 0.92863808],
       [0.80947291, 0.26071842],
       [0.35854517, 0.31760414]])]
[[0.46160127 0.89963258]
 [0.41333744 0.75996015]
 [0.67025035 0.47658527]
 [0.91930096 0.43668071]
 [0.71748236 0.25528005]
 [0.30764393 0.14536158]
 [0.8710383  0.63843333]
 [0.65006316 0.0945142 ]
 [0.80291679 0.45929576]
 [0.76066655 0.38980491]
 [0.83496118 0.44144712]
 [0.39277973 0.02290792]
 [0.40894774 0.46248443]
 [0.34993